name: Publish Package
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write # 用于 Changesets 创建 PR
  id-token: write
  deployments: write

concurrency: ${{ github.workflow }}-${{ github.ref }} # 避免重复发布，旧的action运行完成后才会执行新的

jobs:
  release:
    name: Release & Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 必须获取完整历史，Changesets 才能计算变更
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 24 # 必须大于22才能支持OIDC
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"
      - run: pnpm install --frozen-lockfile
      - name: Create Release PR or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # for write repo
